# Generated by Django 3.0.5 on 2020-06-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DayByDay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_item_text', models.CharField(max_length=300)),
            ],
        ),
    ]
