# Generated by Django 3.0.3 on 2020-03-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200328_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='description',
        ),
        migrations.AddField(
            model_name='todo',
            name='bible_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='todo',
            name='prayer_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='todo',
            name='question_text',
            field=models.TextField(default=''),
        ),
    ]
